import type { LifeEventProcedure, OfficeInfo } from '../types'

export const OFFICES: Record<string, OfficeInfo> = {
  dgep: {
    name: 'Direcția de Evidență a Persoanelor Cluj-Napoca',
    address: 'Str. Moților 3, Cluj-Napoca',
    hours: 'Luni–Vineri: 08:30–16:00 | Marți și Joi: până la 18:00',
    phone: '0264-597.670',
    notes: 'Aduceți documentele originale plus câte o fotocopie.',
  },
  drpciv: {
    name: 'DRPCIV Cluj — Înmatriculări și Permise',
    address: 'Str. Traian Vuia 1-4, Cluj-Napoca',
    hours: 'Luni–Vineri: 08:00–16:00',
    phone: '0264-420.464',
    notes: 'Programare online recomandată pe politiaromana.ro.',
  },
  primarie: {
    name: 'Primăria Municipiului Cluj-Napoca — Taxe și Impozite',
    address: 'Calea Moților 3, Cluj-Napoca',
    hours: 'Luni–Joi: 08:00–16:00 | Vineri: 08:00–13:00',
    phone: '0264-596.030',
    notes: 'Puteți plăti impozitele și pe ghiseu.ro fără deplasare.',
  },
  notar: {
    name: 'Birou Notarial (orice notar autorizat)',
    address: 'Orice birou notarial din Cluj-Napoca',
    hours: 'Luni–Vineri: 09:00–17:00',
    phone: 'Variabil — sunați înainte',
    notes: null,
  },
  cnas_cluj: {
    name: 'Casa de Asigurări de Sănătate Cluj',
    address: 'Str. Constanța 5, Cluj-Napoca',
    hours: 'Luni–Vineri: 08:30–16:30',
    phone: '0264-531.155',
    notes: 'Transferul medicului de familie se face direct la noul cabinet.',
  },
  anaf_cluj: {
    name: 'Agenția Națională de Administrare Fiscală — Cluj',
    address: 'Str. Gh. Doja 67, Cluj-Napoca',
    hours: 'Luni–Vineri: 08:00–16:30',
    phone: '0264-591.890',
    notes: 'Orice birou ANAF din țară poate emite certificatul de TVA.',
  },
}

export const LIFE_EVENTS: Record<string, LifeEventProcedure> = {
  bought_car: {
    event_type: 'bought_car',
    title: 'Înmatriculare vehicul cumpărat',
    emoji: '🚗',
    summary: 'Urmează 5 pași oficiali DRPCIV în maximum 30 de zile.',
    total_estimated_time: '1–2 zile lucrătoare',
    steps: [
      {
        order: 1,
        title: 'Completezi Cererea solicitantului',
        office: 'DRPCIV Cluj — Înmatriculări Auto',
        address: 'Str. Traian Vuia 1-4, Cluj-Napoca',
        hours: 'Luni–Vineri: 08:00–16:00',
        phone: '0264-420.464',
        documents: [
          'Cererea solicitantului (formularul DRPCIV — îl generăm noi completat)',
        ],
        fee: 'Gratuit',
        deadline: 'Înainte de a merge la DRPCIV',
        form_type: 'cerere_drpciv',
        category: 'docs',
        payment_url: null,
        tip: 'Generează cererea din aplicație cu datele tale pre-completate, tipărește și semnează-o. O vei depune la ghișeu împreună cu celelalte documente.',
        online_action: {
          label: 'Descarcă cererea completată',
          type: 'pdf',
          form_type: 'cerere_drpciv',
        },
      },
      {
        order: 2,
        title: 'Autentifici contractul de vânzare-cumpărare',
        office: 'Birou Notarial',
        address: 'Orice birou notarial din Cluj-Napoca',
        hours: 'Luni–Vineri: 09:00–17:00',
        phone: 'Variabil',
        documents: [
          'Buletin vânzător (original)',
          'Buletin cumpărător (original — al tău)',
          'CIV — Cartea de identitate a vehiculului (original)',
          'Contractul de vânzare-cumpărare completat și semnat de ambele părți',
        ],
        fee: '150–300 RON (tarif notarial)',
        deadline: 'Înainte de pasul 3',
        form_type: 'sale_contract',
        category: 'onsite',
        payment_url: null,
        tip: 'Generează contractul din aplicație cu datele tale completate. Tipărește, semnează cu vânzătorul, mergi la notar.',
        online_action: {
          label: 'Generează contract de vânzare',
          type: 'pdf',
          form_type: 'sale_contract',
        },
      },
      {
        order: 3,
        title: 'Plătești taxele DRPCIV',
        office: 'ghiseu.ro (online) sau Trezorerie',
        address: 'Online: https://www.ghiseu.ro',
        hours: 'Disponibil 24/7 online',
        phone: 'N/A',
        documents: [
          'Chitanța / dovada plății (13 RON taxă timbru + 87 RON taxă înmatriculare)',
        ],
        fee: '100 RON total (13 + 87)',
        deadline: 'Înainte de programarea la DRPCIV',
        form_type: null,
        category: 'financial',
        payment_url: 'https://www.ghiseu.ro',
        tip: 'Plătește online pe ghiseu.ro pentru a evita deplasarea la trezorerie.',
        online_action: {
          label: 'Plătește pe ghiseu.ro',
          type: 'url',
          url: 'https://www.ghiseu.ro',
        },
      },
      {
        order: 4,
        title: 'Depui dosarul la DRPCIV',
        office: 'DRPCIV Cluj — Înmatriculări Auto',
        address: 'Str. Traian Vuia 1-4, Cluj-Napoca',
        hours: 'Luni–Vineri: 08:00–16:00',
        phone: '0264-420.464',
        documents: [
          'Cererea solicitantului tipărită și semnată (de la pasul 1)',
          'Buletin (original + copie)',
          'Contract de vânzare-cumpărare autentificat la notar (original + copie)',
          'CIV — Cartea de identitate a vehiculului (original)',
          'ITP valabil (original)',
          'RCA valabil (original sau copie)',
          'Dovada plății taxei (chitanță de la pasul 3)',
        ],
        fee: 'Inclus în taxa plătită la pasul 3',
        deadline: 'În maximum 30 de zile de la cumpărare',
        form_type: null,
        category: 'onsite',
        payment_url: null,
        tip: 'Programează-te online pe politiaromana.ro cu cel puțin 3 zile înainte pentru a evita coada.',
        online_action: {
          label: 'Programare online DRPCIV',
          type: 'appointment',
          url: 'https://www.drpciv.ro/drpciv-booking/activities/21',
          office: 'DRPCIV Cluj — Înmatriculări Auto',
          slot_hint: 'Luni–Vineri 08:00–15:30',
        },
      },
      {
        order: 5,
        title: 'Declari mașina pentru impozit auto',
        office: 'Primăria Cluj-Napoca — Taxe și Impozite',
        address: 'Calea Moților 3, Cluj-Napoca',
        hours: 'Luni–Joi: 08:00–16:00 | Vineri: 08:00–13:00',
        phone: '0264-596.030',
        documents: [
          'Buletin (original + copie)',
          'Noul certificat de înmatriculare (original + copie)',
          'Contract de vânzare-cumpărare (copie)',
          'Declarație impozit auto (o generăm noi)',
        ],
        fee: 'Calculat după cilindree și combustibil',
        deadline: 'În maximum 30 de zile de la înmatriculare',
        form_type: 'impozit_auto',
        category: 'financial',
        payment_url: 'https://www.ghiseu.ro',
        tip: 'După declarare, poți plăti impozitul direct pe ghiseu.ro.',
        online_action: {
          label: 'Descarcă declarație impozit',
          type: 'pdf',
          form_type: 'impozit_auto',
        },
      },
    ],
  },
  moving_to_cluj: {
    event_type: 'moving_to_cluj',
    title: 'Te muți la Cluj pentru facultate',
    emoji: '🎓',
    summary: '4 pași pentru a te instala complet în Cluj.',
    total_estimated_time: 'Prima săptămână',
    steps: [
      {
        order: 1,
        title: 'Viză de flotant sau schimbare buletin',
        category: 'docs',
        office: 'Direcția de Evidență a Persoanelor Cluj-Napoca',
        address: 'Str. Moților 3, Cluj-Napoca',
        hours: 'Luni–Vineri: 08:30–16:00 | Marți și Joi: până la 18:00',
        phone: '0264-597.670',
        documents: [
          'Buletin (original + copie)',
          'Contract de închiriere sau adeverință de la proprietar',
          'Cerere tip (o generăm noi, completată cu datele tale)',
        ],
        fee: 'Gratuit',
        deadline: 'În 15 zile de la instalarea la noua adresă',
        form_type: 'viza_flotant',
        payment_url: null,
        tip: 'Dacă stai la cămin, cere adeverință de la administrația căminului.',
        online_action: {
          label: 'Descarcă cerere viza de flotant',
          type: 'pdf',
          form_type: 'viza_flotant',
        },
      },
      {
        order: 2,
        title: 'Transfer la medic de familie în Cluj',
        category: 'onsite',
        office: 'Cabinet medicină de familie (rețea CNAS)',
        address: 'Orice cabinet din rețeaua CNAS din Cluj',
        hours: 'Luni–Vineri: 08:00–15:00',
        phone: 'Variabil pe cabinet',
        documents: [
          'Buletin (original)',
          'Card de sănătate CNAS (original)',
        ],
        fee: 'Gratuit',
        deadline: 'Recomandat în prima lună',
        form_type: 'doctor_transfer',
        payment_url: null,
        tip: 'Nu ai nevoie de adeverință de la medicul vechi. Mergi direct la noul cabinet.',
        online_action: {
          label: 'Descarcă cerere transfer medic',
          type: 'pdf',
          form_type: 'doctor_transfer',
        },
      },
      {
        order: 3,
        title: 'Abonament CTP student',
        category: 'financial',
        office: 'CTP Cluj-Napoca',
        address: 'Piața Mihai Viteazu 16, Cluj-Napoca',
        hours: 'Luni–Vineri: 07:00–19:00 | Sâmbătă: 08:00–14:00',
        phone: '0264-430.917',
        documents: [
          'Buletin (original)',
          'Legitimație student valabilă cu viză pe semestrul curent',
        ],
        fee: '20–25 RON/lună pentru studenți',
        deadline: 'Oricând',
        form_type: null,
        payment_url: null,
        tip: null,
      },
      {
        order: 4,
        title: 'Adeverință pentru bursă de la primăria de acasă',
        category: 'docs',
        office: 'Primăria din orașul tău natal',
        address: 'Variabil — orașul tău de domiciliu',
        hours: 'Variabil',
        phone: 'Variabil',
        documents: [
          'Cerere tip (o generăm noi)',
          'Buletin',
        ],
        fee: 'Gratuit sau taxă mică de timbru',
        deadline: 'Conform secretariatul universității',
        form_type: 'scholarship_certificate',
        payment_url: null,
        tip: 'Trimite cererea generată de noi pe email la primăria de acasă.',
        online_action: {
          label: 'Descarcă cerere adeverință bursă',
          type: 'pdf',
          form_type: 'scholarship_certificate',
        },
      },
    ],
  },
  id_renewal: {
    event_type: 'id_renewal',
    title: 'Îți reînnoiești buletinul',
    emoji: '🪪',
    summary: 'Reînnoirea buletinului se face la DGEP din județul de domiciliu.',
    total_estimated_time: '30 minute la ghișeu',
    steps: [
      {
        order: 1,
        title: 'Depui cererea la DGEP',
        category: 'onsite',
        office: 'Direcția de Evidență a Persoanelor Cluj-Napoca',
        address: 'Str. Moților 3, Cluj-Napoca',
        hours: 'Luni–Vineri: 08:30–16:00',
        phone: '0264-597.670',
        documents: [
          'Buletin vechi sau expirat (original)',
          'Certificat de naștere (original + copie)',
          'Certificat de căsătorie dacă e cazul (original + copie)',
          'Dovada adresei (dacă adresa s-a schimbat): contract chirie sau act proprietate',
          'Chitanță plată taxă (7 RON la CEC sau online)',
          'Cerere tip (o generăm noi)',
        ],
        fee: '7 RON',
        deadline: 'Înainte de expirare sau în 15 zile după',
        form_type: 'viza_flotant',
        payment_url: null,
        tip: 'Buletinul se eliberează în 30 de zile. Poți solicita emitere urgentă în 3 zile pentru 17 RON.',
      },
    ],
  },
  start_business: {
    event_type: 'start_business',
    title: 'Vrei să deschizi o firmă sau PFA',
    emoji: '💼',
    summary: 'Înregistrarea unei firme se face la Registrul Comerțului.',
    total_estimated_time: '3–5 zile lucrătoare',
    steps: [
      {
        order: 1,
        title: 'Rezervare denumire firmă la ONRC',
        category: 'financial',
        office: 'Oficiul Registrului Comerțului Cluj',
        address: 'Str. Dorobanților 2, Cluj-Napoca',
        hours: 'Luni–Vineri: 09:00–14:00',
        phone: '0264-590.500',
        documents: [
          'Cerere rezervare denumire (online sau la ghișeu)',
          'Buletin',
        ],
        fee: '72 RON',
        deadline: 'Rezervarea e valabilă 3 luni',
        form_type: null,
        payment_url: 'https://www.onrc.ro',
        tip: 'Rezervarea se poate face și 100% online pe portalul ONRC.',
      },
      {
        order: 2,
        title: 'Pregătești actele constitutive și le autentifici',
        category: 'docs',
        office: 'Birou Notarial',
        address: 'Orice birou notarial',
        hours: 'Luni–Vineri: 09:00–17:00',
        phone: 'Variabil',
        documents: [
          'Act constitutiv (îl generăm noi)',
          'Buletin asociați',
          'Dovada sediului social',
        ],
        fee: '200–400 RON',
        deadline: 'După rezervarea denumirii',
        form_type: null,
        payment_url: null,
        tip: null,
      },
    ],
  },
  car_domestic: {
    event_type: 'car_domestic',
    title: 'Ai cumpărat o mașină în România',
    emoji: '🚗',
    summary: '4 pași pentru a înmatricula mașina cumpărată în România.',
    total_estimated_time: '1–2 zile lucrătoare',
    steps: [
      {
        order: 1,
        title: 'Autentifici contractul de vânzare-cumpărare',
        category: 'docs',
        office: 'Orice birou notarial din Cluj-Napoca',
        address: 'Orice notar — verifică harta notarilor',
        hours: 'Luni–Vineri: 09:00–17:00',
        phone: 'Variabil — sunați înainte',
        documents: [
          'Buletin vânzător (original)',
          'Buletin cumpărător (original)',
          'CIV original',
          'Contract completat și semnat',
        ],
        fee: '150–300 RON',
        deadline: 'Înainte de pasul 2',
        form_type: 'sale_contract',
        payment_url: null,
        tip: 'Generăm contractul pre-completat cu datele tale. Tipărește, semnează cu vânzătorul, mergi la notar.',
        online_action: {
          label: 'Descarcă contract pre-completat',
          type: 'pdf',
          form_type: 'sale_contract',
        },
      },
      {
        order: 2,
        title: 'Transcrieri mașina la DRPCIV',
        category: 'onsite',
        office: 'DRPCIV Cluj — Înmatriculări',
        address: 'Str. Traian Vuia 1-4, Cluj-Napoca',
        hours: 'Luni–Vineri: 08:00–16:00',
        phone: '0264-420.464',
        documents: [
          'Buletin (original + copie)',
          'Contract autentificat (original + copie)',
          'CIV original',
          'ITP valabil',
          'RCA valabil',
          'Dovada plată 49 RON certificat (ghișeu.ro)',
        ],
        fee: '49 RON certificat + ~200 RON plăcuțe',
        deadline: 'În 30 de zile de la cumpărare — penalizare după',
        form_type: 'transcription',
        payment_url: 'https://www.ghiseul.ro',
        tip: 'Plătește taxa de 49 RON pe ghișeu.ro înainte să mergi la ghișeu — este obligatoriu. Descarcă și cererea de transcriere pre-completată.',
        online_action: {
          label: 'Rezervă programare DRPCIV',
          type: 'appointment',
          office: 'DRPCIV Cluj — Înmatriculări',
          slot_hint: 'Marți–Joi dimineața',
          url: 'https://www.drpciv.ro/drpciv-booking/activities/21',
        },
      },
      {
        order: 3,
        title: 'Declari mașina la Primărie pentru impozit auto',
        category: 'financial',
        office: 'Primăria Cluj-Napoca — Taxe și Impozite',
        address: 'Calea Moților 3, Cluj-Napoca',
        hours: 'Luni–Joi: 08:00–16:00 | Vineri: 08:00–13:00',
        phone: '0264-596.030',
        documents: [
          'Buletin (original + copie)',
          'Certificat înmatriculare nou (original + copie)',
          'Contract vânzare (copie)',
        ],
        fee: 'Gratuit (impozit calculat separat)',
        deadline: 'În 30 de zile de la înmatriculare',
        form_type: 'impozit_auto',
        payment_url: 'https://www.ghiseul.ro',
        tip: 'Poți plăti impozitul direct pe ghișeu.ro după declarare, fără a reveni la ghișeu.',
        online_action: {
          label: 'Descarcă declarație + plătește impozit (simulare)',
          type: 'payment',
          amount_ron: 150,
          description: 'Impozit auto estimat anual',
          url: 'https://www.ghiseul.ro',
        },
      },
      {
        order: 4,
        title: 'Cumpără asigurare RCA pe numele tău',
        category: 'financial',
        office: 'Online — orice asigurător autorizat ASF',
        address: 'Online',
        hours: 'Disponibil 24/7',
        phone: 'Nu este necesar',
        documents: ['Buletin', 'Certificat de înmatriculare'],
        fee: 'Variabil — de la ~400 RON/an',
        deadline: 'Înainte de pasul 2',
        form_type: null,
        payment_url: 'https://www.ieftine.ro/asigurari/rca',
        tip: 'Compară prețurile înainte de a cumpăra. RCA trebuie să fie pe numele noului proprietar.',
        online_action: {
          label: 'Compară prețuri RCA',
          type: 'url',
          url: 'https://www.ieftine.ro/asigurari/rca',
        },
      },
    ],
  },
  car_from_germany: {
    event_type: 'car_from_germany',
    title: 'Înmatriculare mașină din Germania/UE',
    emoji: '🇩🇪',
    summary: '7 pași pentru a înmatricula o mașină adusă din Germania sau altă țară UE. Estimat total: ~1.150 RON.',
    total_estimated_time: '2–3 săptămâni',
    steps: [
      {
        order: 1,
        title: 'Traduci documentele germane la traducător autorizat',
        category: 'docs',
        office: 'Traducător autorizat (online sau fizic)',
        address: 'Online sau orice birou traduceri autorizate',
        hours: 'Variabil',
        phone: 'Variabil',
        documents: [
          'Brief mare (Teil II / Fahrzeugbrief)',
          'Factura de cumpărare sau Kaufvertrag',
        ],
        fee: '150–300 RON',
        deadline: 'Primul pas — blocant pentru toate celelalte',
        form_type: null,
        payment_url: null,
        tip: 'Trimitem online documentele și datele tale către un furnizor de traduceri autorizate, după ce confirmi explicit partajarea datelor.',
        online_action: {
          label: 'Solicită traducere autorizată online',
          type: 'translation_quote',
          provider: 'wetranslate',
          url: 'https://www.wetranslate.ro/oferta/?page=49_1',
          source_language: 'Germană',
          target_language: 'Română',
          package: 'Optimal',
        },
      },
      {
        order: 2,
        title: 'Programare și vizită RAR — omologare, ITP, CIV',
        category: 'onsite',
        office: 'Registrul Auto Român Cluj',
        address: 'Str. Taietura Turcului 12A, Cluj-Napoca',
        hours: 'Luni–Vineri: 08:00–16:00 (cu programare)',
        phone: '0264-432.474',
        documents: [
          'Brief mare tradus (original)',
          'Factura/Kaufvertrag tradus',
          'Buletin',
          'CoC (dacă mașina e după aug 2018)',
        ],
        fee: '750 RON (ITP 250 + CIV 250 + autenticitate 250) | +500 RON dacă lipsește CoC',
        deadline: 'Înainte de pasul 3 — CIV e necesar la ANAF și DRPCIV',
        form_type: null,
        payment_url: null,
        tip: 'Dacă mașina nu are plăcuțe valabile de export (Zollkennzeichen), nu o poți conduce la RAR. Scoate numere roșii mai întâi de la DRPCIV.',
        online_action: {
          label: 'Rezervă programare RAR',
          type: 'appointment',
          office: 'Registrul Auto Român Cluj',
          slot_hint: 'Luni–Vineri 08:00–12:00',
          url: 'https://www.rar.ro',
        },
      },
      {
        order: 3,
        title: 'Obții certificatul TVA de la ANAF',
        category: 'docs',
        office: 'ANAF Cluj sau online prin SPV',
        address: 'Str. Mihail Kogălniceanu 10, Cluj-Napoca',
        hours: 'Luni–Vineri: 08:30–16:30',
        phone: '0264-415.551',
        documents: [
          'Cerere tip ANAF (o generăm noi)',
          'Buletin',
          'Brief mare tradus',
          'Factura tradusă',
          'CIV (de la RAR)',
        ],
        fee: 'Gratuit',
        deadline: 'Înainte de pasul 7 (DRPCIV)',
        form_type: 'anaf_tva_certificate',
        payment_url: null,
        tip: 'Dacă ai cont SPV, poți depune cererea online. Pentru mașini SH de la persoană fizică, TVA este de regulă 0 RON — certificatul doar confirmă acest lucru.',
        online_action: {
          label: 'Descarcă cerere certificat TVA ANAF',
          type: 'pdf',
          form_type: 'anaf_tva_certificate',
        },
      },
      {
        order: 4,
        title: 'Înregistrare la Primărie — ștampilă REMTII + impozit auto',
        category: 'onsite',
        office: 'Primăria Cluj-Napoca — Taxe și Impozite',
        address: 'Calea Moților 3, Cluj-Napoca',
        hours: 'Luni–Joi: 08:00–16:00 | Vineri: 08:00–13:00',
        phone: '0264-596.030',
        documents: [
          'Contract tradus (trebuie să primească numărul REMTII)',
          'Buletin',
          'CIV (de la RAR)',
          'Declarație impozit auto (o generăm noi)',
        ],
        fee: 'Gratuit (impozit calculat separat)',
        deadline: 'Înainte de pasul 7 — DRPCIV verifică numărul REMTII pe contract',
        form_type: 'impozit_auto',
        payment_url: 'https://www.ghiseul.ro',
        tip: 'Numărul REMTII trebuie să apară pe contract când mergi la DRPCIV. Adă toate documentele la acest ghișeu într-o singură vizită.',
        online_action: {
          label: 'Descarcă declarație impozit auto',
          type: 'pdf',
          form_type: 'impozit_auto',
        },
      },
      {
        order: 5,
        title: 'Plătești taxele DRPCIV pe ghișeu.ro',
        category: 'financial',
        office: 'Online — ghișeu.ro',
        address: 'Online',
        hours: 'Disponibil 24/7',
        phone: 'Nu este necesar',
        documents: ['CNP', 'Serie șasiu (VIN)'],
        fee: '49 RON certificat înmatriculare + ~200 RON plăcuțe',
        deadline: 'Înainte de programarea DRPCIV — plata e obligatorie la ghișeu',
        form_type: null,
        payment_url: 'https://www.ghiseul.ro',
        tip: 'Achită ambele taxe pe ghișeu.ro și salvează chitanțele. La DRPCIV se verifică plata electronic — nu mai trebuie să aduci chitanță pe hârtie.',
        online_action: {
          label: 'Plătește taxele DRPCIV (simulare)',
          type: 'payment',
          amount_ron: 249,
          description: 'Certificat înmatriculare + plăcuțe',
          url: 'https://www.ghiseul.ro',
        },
      },
      {
        order: 6,
        title: 'Cumperi asigurare RCA pe numele tău',
        category: 'financial',
        office: 'Online',
        address: 'Online',
        hours: '24/7',
        phone: 'Nu este necesar',
        documents: ['Buletin', 'CIV (de la RAR)'],
        fee: 'Variabil — de la ~400 RON/an',
        deadline: 'Înainte de programarea DRPCIV',
        form_type: null,
        payment_url: 'https://www.ieftine.ro/asigurari/rca',
        tip: 'RCA-ul trebuie să fie pe numele tău (noul proprietar) nu al celui de la care ai cumpărat. Poți cumpăra 100% online.',
        online_action: {
          label: 'Compară și cumpără RCA',
          type: 'url',
          url: 'https://www.ieftine.ro/asigurari/rca',
        },
      },
      {
        order: 7,
        title: 'Programare și depunere dosar final la DRPCIV',
        category: 'onsite',
        office: 'DRPCIV Cluj — Înmatriculări',
        address: 'Str. Traian Vuia 1-4, Cluj-Napoca',
        hours: 'Luni–Vineri: 08:00–16:00',
        phone: '0264-420.464',
        documents: [
          'Cerere tip DRPCIV (o generăm noi)',
          'Buletin original + copie',
          'Contract tradus cu ștampilă REMTII',
          'CIV original (de la RAR)',
          'ITP valabil (de la RAR)',
          'RCA valabil (pe numele tău)',
          'Certificat autenticitate (de la RAR)',
          'Certificat TVA ANAF',
          'Chitanță 49 RON certificat',
          'Chitanță ~200 RON plăcuțe',
        ],
        fee: 'Taxele deja plătite în pasul 5',
        deadline: 'În 30 de zile de la intrarea mașinii în România',
        form_type: 'cerere_drpciv',
        payment_url: null,
        tip: 'Dosarul complet la DRPCIV durează 30–45 minute. Dacă ai toate actele din lista de mai sus, nu vei fi trimis înapoi.',
        online_action: {
          label: 'Rezervă programare DRPCIV',
          type: 'appointment',
          office: 'DRPCIV Cluj — Înmatriculări',
          slot_hint: 'După plata taxelor',
          url: 'https://www.drpciv.ro/drpciv-booking/activities/21',
        },
      },
    ],
  },
}

export function findProcedure(eventType: string): LifeEventProcedure | null {
  return LIFE_EVENTS[eventType] ?? null
}

export function detectEventType(message: string): string | null {
  const msg = message.toLowerCase()

  // Car from Germany / EU (higher priority than generic bought_car)
  if (
    (msg.includes('mașin') || msg.includes('masin') || msg.includes('auto')) &&
    (msg.includes('germania') || msg.includes('germani') || msg.includes('ue') ||
     msg.includes('europa') || msg.includes('intracomunitara') || msg.includes('import') ||
     msg.includes('din afar') || msg.includes('din strain'))
  )
    return 'car_from_germany'

  // Generic domestic car purchase
  if (
    msg.includes('mașin') ||
    msg.includes('masin') ||
    msg.includes('auto') ||
    msg.includes('cumpărat') ||
    msg.includes('cumparat')
  )
    return 'car_domestic'

  if (
    msg.includes('facultate') ||
    msg.includes('universitate') ||
    msg.includes('mut') ||
    msg.includes('cluj')
  )
    return 'moving_to_cluj'
  if (
    msg.includes('buletin') ||
    msg.includes('act de identitate') ||
    msg.includes('reînnoi') ||
    msg.includes('reinnoi') ||
    msg.includes('expirat')
  )
    return 'id_renewal'
  if (
    msg.includes('firmă') ||
    msg.includes('firma') ||
    msg.includes('pfa') ||
    msg.includes('srl') ||
    msg.includes('afacere')
  )
    return 'start_business'
  return null
}
