/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeedRouteImport } from './routes/seed'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OurGoalRouteImport } from './routes/our-goal'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NewsRouteImport } from './routes/news'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DocumentPreviewRouteImport } from './routes/document-preview'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ActionPlanRouteImport } from './routes/action-plan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LifeEventIdRouteImport } from './routes/life-event.$id'
import { Route as DrpcivEventIdRouteImport } from './routes/drpciv.$eventId'
import { Route as ChatConversationIdRouteImport } from './routes/chat.$conversationId'
import { Route as AdminNewsRouteImport } from './routes/admin.news'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedRoute = SeedRouteImport.update({
  id: '/seed',
  path: '/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OurGoalRoute = OurGoalRouteImport.update({
  id: '/our-goal',
  path: '/our-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentPreviewRoute = DocumentPreviewRouteImport.update({
  id: '/document-preview',
  path: '/document-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlanRoute = ActionPlanRouteImport.update({
  id: '/action-plan',
  path: '/action-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeEventIdRoute = LifeEventIdRouteImport.update({
  id: '/life-event/$id',
  path: '/life-event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DrpcivEventIdRoute = DrpcivEventIdRouteImport.update({
  id: '/drpciv/$eventId',
  path: '/drpciv/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatConversationIdRoute = ChatConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => ChatRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/document-preview': typeof DocumentPreviewRoute
  '/documents': typeof DocumentsRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/our-goal': typeof OurGoalRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/report': typeof ReportRoute
  '/seed': typeof SeedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/admin/news': typeof AdminNewsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/drpciv/$eventId': typeof DrpcivEventIdRoute
  '/life-event/$id': typeof LifeEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/document-preview': typeof DocumentPreviewRoute
  '/documents': typeof DocumentsRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/our-goal': typeof OurGoalRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/report': typeof ReportRoute
  '/seed': typeof SeedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/admin/news': typeof AdminNewsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/drpciv/$eventId': typeof DrpcivEventIdRoute
  '/life-event/$id': typeof LifeEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/document-preview': typeof DocumentPreviewRoute
  '/documents': typeof DocumentsRoute
  '/news': typeof NewsRoute
  '/onboarding': typeof OnboardingRoute
  '/our-goal': typeof OurGoalRoute
  '/plans': typeof PlansRoute
  '/profile': typeof ProfileRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/report': typeof ReportRoute
  '/seed': typeof SeedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/admin/news': typeof AdminNewsRoute
  '/chat/$conversationId': typeof ChatConversationIdRoute
  '/drpciv/$eventId': typeof DrpcivEventIdRoute
  '/life-event/$id': typeof LifeEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-plan'
    | '/audit'
    | '/auth'
    | '/chat'
    | '/document-preview'
    | '/documents'
    | '/news'
    | '/onboarding'
    | '/our-goal'
    | '/plans'
    | '/profile'
    | '/profile-setup'
    | '/report'
    | '/seed'
    | '/sitemap.xml'
    | '/staff'
    | '/admin/news'
    | '/chat/$conversationId'
    | '/drpciv/$eventId'
    | '/life-event/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-plan'
    | '/audit'
    | '/auth'
    | '/chat'
    | '/document-preview'
    | '/documents'
    | '/news'
    | '/onboarding'
    | '/our-goal'
    | '/plans'
    | '/profile'
    | '/profile-setup'
    | '/report'
    | '/seed'
    | '/sitemap.xml'
    | '/staff'
    | '/admin/news'
    | '/chat/$conversationId'
    | '/drpciv/$eventId'
    | '/life-event/$id'
  id:
    | '__root__'
    | '/'
    | '/action-plan'
    | '/audit'
    | '/auth'
    | '/chat'
    | '/document-preview'
    | '/documents'
    | '/news'
    | '/onboarding'
    | '/our-goal'
    | '/plans'
    | '/profile'
    | '/profile-setup'
    | '/report'
    | '/seed'
    | '/sitemap.xml'
    | '/staff'
    | '/admin/news'
    | '/chat/$conversationId'
    | '/drpciv/$eventId'
    | '/life-event/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionPlanRoute: typeof ActionPlanRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRouteWithChildren
  DocumentPreviewRoute: typeof DocumentPreviewRoute
  DocumentsRoute: typeof DocumentsRoute
  NewsRoute: typeof NewsRoute
  OnboardingRoute: typeof OnboardingRoute
  OurGoalRoute: typeof OurGoalRoute
  PlansRoute: typeof PlansRoute
  ProfileRoute: typeof ProfileRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  ReportRoute: typeof ReportRoute
  SeedRoute: typeof SeedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRoute
  AdminNewsRoute: typeof AdminNewsRoute
  DrpcivEventIdRoute: typeof DrpcivEventIdRoute
  LifeEventIdRoute: typeof LifeEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seed': {
      id: '/seed'
      path: '/seed'
      fullPath: '/seed'
      preLoaderRoute: typeof SeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-goal': {
      id: '/our-goal'
      path: '/our-goal'
      fullPath: '/our-goal'
      preLoaderRoute: typeof OurGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/document-preview': {
      id: '/document-preview'
      path: '/document-preview'
      fullPath: '/document-preview'
      preLoaderRoute: typeof DocumentPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plan': {
      id: '/action-plan'
      path: '/action-plan'
      fullPath: '/action-plan'
      preLoaderRoute: typeof ActionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life-event/$id': {
      id: '/life-event/$id'
      path: '/life-event/$id'
      fullPath: '/life-event/$id'
      preLoaderRoute: typeof LifeEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drpciv/$eventId': {
      id: '/drpciv/$eventId'
      path: '/drpciv/$eventId'
      fullPath: '/drpciv/$eventId'
      preLoaderRoute: typeof DrpcivEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$conversationId': {
      id: '/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof ChatConversationIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatConversationIdRoute: typeof ChatConversationIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatConversationIdRoute: ChatConversationIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionPlanRoute: ActionPlanRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRouteWithChildren,
  DocumentPreviewRoute: DocumentPreviewRoute,
  DocumentsRoute: DocumentsRoute,
  NewsRoute: NewsRoute,
  OnboardingRoute: OnboardingRoute,
  OurGoalRoute: OurGoalRoute,
  PlansRoute: PlansRoute,
  ProfileRoute: ProfileRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  ReportRoute: ReportRoute,
  SeedRoute: SeedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRoute,
  AdminNewsRoute: AdminNewsRoute,
  DrpcivEventIdRoute: DrpcivEventIdRoute,
  LifeEventIdRoute: LifeEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
